# Build script
init:
  - git config --global core.autocrlf true

# Clone submodules
install:
  - git submodule update --init --recursive

image: Visual Studio 2017

# Build script
build_script:
  - ps: .\build.ps1 -Target AppVeyor -Verbosity Diagnostic

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - master
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/
    - /improve/.*/

# Build cache
cache:
- tools -> setup.cake
- src/packages -> setup.cake