''------------------------------------------------------------------------------ 
'' <auto-generated> 
'' This code was generated by HgVersion. 
'' 
'' You can modify this code as we will not overwrite it when re-executing HgVersion
'' </auto-generated> 
''------------------------------------------------------------------------------

Imports System.Reflection

<Assembly: AssemblyFileVersion("0.0.0.0")>
<Assembly: AssemblyVersion("0.0.0.0")>
<Assembly: AssemblyInformationalVersion("0.0.0.0")>